version: '3.7'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: collector
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: data-collector
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: collector
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://collector:password@mongo:27017/

volumes:
  mongodb_data_container: