dathost:
  auth:
    username:
    password:
    rcon:
  host: https://dathost.net/api/0.1/
  servers: game-servers
  matches: matches
server:
  port: 8085
spring:
  profiles:
    active: local
kafka:
  producer:
    bootstrap-address: localhost:9092
    topic-name: game-started