spring:
  data:
    mongodb:
      database: data-collector
      port: 27017
      username: collector
      password: password
server:
  port: 8082
security:
  basic:
    enable: false
  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic