spring:
  data:
    mongodb:
      database: data-collector
      port: 27017
      username: collector
      password: password
logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    root: DEBUG

server:
  port: 8082
security:
  basic:
    enable: false
  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic


##Steam API
steam.api.key: F1B93E1BC2DBAA0EC8F3CE4731944B59
steam.api.url: https://steamcommunity.com/openid/
