name: "Push"
on: ["push"]

env:
  REGISTRY: ghcr.io
  YANDEX_REGISTRY: cr.yandex/crpo7u2hcjd8o0fvme6l
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v1"

      - name: "Test"
        run: 'echo "ok"'

      # - name: Log in to the Container registry
      #   uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the Yandex Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.YANDEX_REGISTRY }}
          username: oauth
          password: ${{ secrets.YANDEX_OAUTH_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            ${{ env.YANDEX_REGISTRY }}/${{ env.IMAGE_NAME }}
          # ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: "Deploy"
        uses: "Evgenyguzman/helm@master"
        with:
          token: "${{ github.token }}"
          secrets: "${{ toJSON(secrets) }}"
          version: "${{ github.sha }}"
          chart: "./chart"
          namespace: example-helm
          release: production-payplay-backend
          value-files: "./config/production.yml"
        env:
          KUBECONFIG_FILE: "${{ secrets.KUBECONFIG }}"
